version: '3.8'

services:
  # API Gateway - Nginx Reverse Proxy
  api-gateway:
    image: nginx:1.25-alpine
    container_name: api_gateway
    ports:
      - "80:80"
      - "8081:8081" 
      - "8080:8080"
      - "9090:9090"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - gateway_logs:/var/log/nginx
    
    networks:
      - authservice_authservice_network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  gateway_logs:
    driver: local

networks:
  authservice_authservice_network:
    external: true